# Generated by Django 3.1.4 on 2020-12-03 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Geburtstag', models.DateField()),
                ('Geschlecht', models.CharField(choices=[('1', 'männlich'), ('2', 'weiblich'), ('3', 'divers')], default='1', max_length=6)),
                ('Postleitzahl', models.IntegerField()),
                ('Ort', models.CharField(max_length=100)),
                ('Straße', models.CharField(max_length=100)),
                ('Hausnummer', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
