# Generated by Django 2.2.6 on 2020-12-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAdress', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('postcode', models.IntegerField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('village', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=30)),
                ('yearOfFoundation', models.CharField(max_length=4)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.AdressModel')),
            ],
        ),
        migrations.AddField(
            model_name='adressmodel',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.PlaceModel'),
        ),
    ]
