# Generated by Django 2.2.6 on 2020-12-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=20)),
                ('houseNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('village', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=30)),
                ('yearOfFoundation', models.CharField(max_length=4)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.AddressModel')),
            ],
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.PlaceModel'),
        ),
    ]
