# Generated by Django 2.2.6 on 2020-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='postcode',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
