# Generated by Django 2.2.6 on 2020-12-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20201202_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressModel',
            new_name='AddressModel',
        ),
        migrations.RenameField(
            model_name='addressmodel',
            old_name='streetAdress',
            new_name='streetAddress',
        ),
        migrations.RenameField(
            model_name='clubmodel',
            old_name='adress',
            new_name='address',
        ),
    ]
